global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: exporter
    static_configs:
      - targets: ['localhost:9100']
      - targets: ['media.thundering-ops.com:9100']
      - targets: ['pihole.thundering-ops.com:9100']
  - job_name: pushgateway
    static_configs:
      - targets: ['localhost:9091']
