---
- name: "Add docker GPG key"
  become: true
  become_user: root
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  notify: "Update apt cache"

- name: "Get target DEB architecture"
  ansible.builtin.shell: dpkg --print-architecture
  register: deb_architecture

- name: "Add docker to apt sources"
  become: true
  become_user: root
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  notify: "Update apt cache"

- name: "flush handlers"
  ansible.builtin.meta: flush_handlers

- name: "Install docker"
  become: true
  become_user: root
  ansible.builtin.package:
    name: docker-ce
    state: present

- name: "Make sure docker is started and enabled"
  become: true
  become_user: root
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
