---
- name: "Add docker GPG key"
  block:
    - name: "Get docker's apt key"
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: "Get target DEB architecture"
      ansible.builtin.shell: dpkg --print-architecture
      register: deb_architecture

    - name: "Add docker to apt sources"
      become: true
      become_user: root
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      notify: "Update apt cache"

- name: "Install docker"
  become: true
  become_user: root
  ansible.builtin.package:
    name: docker-ce
    state: present

- name: "Make sure docker is started and enabled"
  become: true
  become_user: root
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
