---
# tasks file for install-k8s
- block:
   - name: "[PREREQUISITES] Set variables"
     ansible.builtin.include_vars:
      file: "../vars/main.yml"
      name: variables

   - name: "[PREREQUISITES] IP forwarding"
     ansible.builtin.include_tasks: "host-networking/ip-forward.yml"

   - name: "[PREREQUISITES] Install packages"
     become: true
     become_user: root
     ansible.builtin.package:
       name: "{{ item }}"
       state: present
     loop: "{{ packages }}"

   - name: "[PREREQUISITES] Install container runtime"
     ansible.builtin.include_tasks: "runtimes/install-{{ cluster.container_runtime_name }}.yml"

   - name: "Install kube* binaries"
     ansible.builtin.include_tasks: "install-kube_binaries.yml"
