---
- name: "Set traffic forward in /etc/sysctl.conf"
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: "^#net.ipv4.ip_forward"
    line: "net.ipv4.ip_forward = 1"

- name: "Enable ip forward"
  become: true
  become_user: root
  ansible.builtin.shell: |
    sysctl -p

- name: "Fix br_netfilter"
  become: true
  become_user: root
  ansible.builtin.shell: |
    echo "br_netfilter" >> /etc/modules
    modprobe br_netfilter
