---
- name: "[Create node exporter directory]"
  ansible.builtin.file:
    path: "{{ NODE_EXPORTER_ARCHIVE_DIRECTORY  }}"
    state: directory

- name: "[Create user]"
  ansible.builtin.user:
    name: node_exporter
    state: present

- name: "[Download exporter binary]"
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ NODE_EXPORTER_VERSION }}/node_exporter-{{ NODE_EXPORTER_VERSION }}.linux-amd64.tar.gz"
    dest: "{{ NODE_EXPORTER_ARCHIVE_DESTINATION }}"
    mode: "0644"

- name: "[Unarchive node exporter]"
  ansible.builtin.unarchive:
    src: "{{ NODE_EXPORTER_ARCHIVE_DESTINATION }}"
    dest: "{{ NODE_EXPORTER_ARCHIVE_DIRECTORY }}"
    remote_src: yes

- name: "[move node_exporter binary]"
  ansible.builtin.copy:
    src: "{{ NODE_EXPORTER_ARCHIVE_DIRECTORY }}/node_exporter-{{ NODE_EXPORTER_VERSION }}.linux-amd64/node_exporter"
    dest: "{{ NODE_EXPORTER_BINARY_DESTINATION }}"
    owner: node_exporter
    group: node_exporter
    mode: a+x
    remote_src: yes

- name: "[Copy unit file]"
  ansible.builtin.copy:
    src: "../template/node_exporter.service"
    dest: "/usr/lib/systemd/system/node_exporter.service"
    owner: node_exporter
    group: node_exporter
    mode: "0664"

- name: "[Reload daemon]"
  ansible.builtin.systemd:
    daemon_reload: true

- name: "[Start node_exporter service]"
  ansible.builtin.service:
    name: node_exporter
    state: started

