route:
  group_by: ['alertname', 'job']

  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

  receiver: discord

receivers:
- name: discord
  discord_configs:
  - webhook_url: https://discord.com/api/webhooks/1076649276140171414/Ov-IcKVNtivhP2oEcjwA-FXh3D_P5OvFNSaoD7BcqZdaUjw5XK_xEIF1Nh_Z6APpsJ8G
